from .ModuleBase import *
from .PLA import *
from .LinearRegression import *
from .Fisher import *
from .svm import *
from .LogisticRegression import *
from .multiclass import *
from .mnist import *
from .lenet import *